using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Pulse.Core.Migrations
{
    /// <inheritdoc />
    public partial class AddMoneyMovement : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "MoneyMovements",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    SourceType = table.Column<int>(type: "int", nullable: false),
                    SourceId = table.Column<int>(type: "int", nullable: true),
                    DestinationType = table.Column<int>(type: "int", nullable: false),
                    DestinationId = table.Column<int>(type: "int", nullable: true),
                    Amount = table.Column<decimal>(type: "decimal(18,2)", precision: 18, scale: 2, nullable: false),
                    MovementDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    MovementType = table.Column<int>(type: "int", nullable: false),
                    Note = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                    IsAutoGenerated = table.Column<bool>(type: "bit", nullable: false),
                    RelatedPaymentId = table.Column<int>(type: "int", nullable: true),
                    UserId = table.Column<string>(type: "nvarchar(450)", nullable: true),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_MoneyMovements", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_MoneyMovements_DestinationType_DestinationId",
                table: "MoneyMovements",
                columns: new[] { "DestinationType", "DestinationId" });

            migrationBuilder.CreateIndex(
                name: "IX_MoneyMovements_MovementDate",
                table: "MoneyMovements",
                column: "MovementDate");

            migrationBuilder.CreateIndex(
                name: "IX_MoneyMovements_RelatedPaymentId",
                table: "MoneyMovements",
                column: "RelatedPaymentId",
                filter: "[RelatedPaymentId] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_MoneyMovements_SourceType_SourceId",
                table: "MoneyMovements",
                columns: new[] { "SourceType", "SourceId" });

            migrationBuilder.CreateIndex(
                name: "IX_MoneyMovements_UserId",
                table: "MoneyMovements",
                column: "UserId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "MoneyMovements");
        }
    }
}
