using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pulse.Core.Data;
using Pulse.Core.DTOs;
using Pulse.Core.Models;
using Pulse.Core.Models.Enums;

namespace Pulse.Api.Controllers;

[ApiController]
[Route("api/money-movements")]
[Authorize]
public class MoneyMovementsController : ControllerBase
{
    private readonly PulseDbContext _db;

    public MoneyMovementsController(PulseDbContext db)
    {
        _db = db;
    }

    private string UserId => User.FindFirstValue(ClaimTypes.NameIdentifier)!;

    [HttpGet]
    public async Task<ActionResult> GetAll(
        [FromQuery] MoneyMovementEntityType? entityType,
        [FromQuery] int? entityId,
        [FromQuery] MovementType? movementType,
        [FromQuery] DateTime? from,
        [FromQuery] DateTime? to)
    {
        var query = _db.MoneyMovements.Where(m => m.UserId == UserId).AsQueryable();

        if (entityType.HasValue && entityId.HasValue)
        {
            var et = entityType.Value;
            var eid = entityId.Value;
            query = query.Where(m =>
                (m.SourceType == et && m.SourceId == eid) ||
                (m.DestinationType == et && m.DestinationId == eid));
        }

        if (movementType.HasValue)
            query = query.Where(m => m.MovementType == movementType.Value);

        if (from.HasValue)
            query = query.Where(m => m.MovementDate >= from.Value);

        if (to.HasValue)
            query = query.Where(m => m.MovementDate <= to.Value);

        var movements = await query.OrderByDescending(m => m.MovementDate).ThenByDescending(m => m.Id).ToListAsync();

        var bankIds = movements
            .SelectMany(m => new[] {
                m.SourceType == MoneyMovementEntityType.BankAccount ? m.SourceId : null,
                m.DestinationType == MoneyMovementEntityType.BankAccount ? m.DestinationId : null
            })
            .Where(id => id.HasValue).Select(id => id!.Value).Distinct().ToList();

        var loanIds = movements
            .SelectMany(m => new[] {
                m.SourceType == MoneyMovementEntityType.Loan ? m.SourceId : null,
                m.DestinationType == MoneyMovementEntityType.Loan ? m.DestinationId : null
            })
            .Where(id => id.HasValue).Select(id => id!.Value).Distinct().ToList();

        var cardIds = movements
            .SelectMany(m => new[] {
                m.SourceType == MoneyMovementEntityType.CreditCard ? m.SourceId : null,
                m.DestinationType == MoneyMovementEntityType.CreditCard ? m.DestinationId : null
            })
            .Where(id => id.HasValue).Select(id => id!.Value).Distinct().ToList();

        var bankNames = bankIds.Count > 0
            ? await _db.BankAccounts.Where(a => bankIds.Contains(a.Id) && a.UserId == UserId)
                .ToDictionaryAsync(a => a.Id, a => a.AccountName)
            : new Dictionary<int, string>();

        var loanNames = loanIds.Count > 0
            ? await _db.PersonalLoans.Where(l => loanIds.Contains(l.Id) && l.UserId == UserId)
                .ToDictionaryAsync(l => l.Id, l => l.LenderName)
            : new Dictionary<int, string>();

        var cardNames = cardIds.Count > 0
            ? await _db.CreditCards.Where(c => cardIds.Contains(c.Id) && c.UserId == UserId)
                .ToDictionaryAsync(c => c.Id, c => c.CardName)
            : new Dictionary<int, string>();

        string ResolveName(MoneyMovementEntityType type, int? id) => type switch
        {
            MoneyMovementEntityType.BankAccount when id.HasValue && bankNames.TryGetValue(id.Value, out var n) => n,
            MoneyMovementEntityType.Loan when id.HasValue && loanNames.TryGetValue(id.Value, out var n) => n,
            MoneyMovementEntityType.CreditCard when id.HasValue && cardNames.TryGetValue(id.Value, out var n) => n,
            MoneyMovementEntityType.External => "External",
            _ => "Unknown"
        };

        var result = movements.Select(m => new
        {
            m.Id,
            m.SourceType,
            m.SourceId,
            SourceName = ResolveName(m.SourceType, m.SourceId),
            m.DestinationType,
            m.DestinationId,
            DestinationName = ResolveName(m.DestinationType, m.DestinationId),
            m.Amount,
            m.MovementDate,
            m.MovementType,
            m.Note,
            m.IsAutoGenerated,
            m.RelatedPaymentId,
            m.RelatedExpenseId,
            m.CreatedAt,
            m.UpdatedAt
        });

        return Ok(result);
    }

    [HttpGet("{id}")]
    public async Task<ActionResult> GetById(int id)
    {
        var m = await _db.MoneyMovements.FirstOrDefaultAsync(m => m.Id == id && m.UserId == UserId);
        if (m is null) return NotFound();
        return Ok(m);
    }

    [HttpPost]
    public async Task<ActionResult> Create(MoneyMovementCreateDto dto)
    {
        if (dto.SourceType != MoneyMovementEntityType.External && !dto.SourceId.HasValue)
            return BadRequest(new { message = "SourceId is required when SourceType is not External." });

        if (dto.DestinationType != MoneyMovementEntityType.External && !dto.DestinationId.HasValue)
            return BadRequest(new { message = "DestinationId is required when DestinationType is not External." });

        var movement = new MoneyMovement
        {
            SourceType = dto.SourceType,
            SourceId = dto.SourceId,
            DestinationType = dto.DestinationType,
            DestinationId = dto.DestinationId,
            Amount = dto.Amount,
            MovementDate = dto.MovementDate,
            MovementType = dto.MovementType,
            Note = dto.Note,
            IsAutoGenerated = false,
            UserId = UserId
        };

        _db.MoneyMovements.Add(movement);
        await _db.SaveChangesAsync();

        return CreatedAtAction(nameof(GetById), new { id = movement.Id }, movement);
    }

    [HttpPut("{id}")]
    public async Task<ActionResult> Update(int id, MoneyMovementCreateDto dto)
    {
        var movement = await _db.MoneyMovements.FirstOrDefaultAsync(m => m.Id == id && m.UserId == UserId);
        if (movement is null) return NotFound();

        if (movement.IsAutoGenerated)
            return BadRequest(new { message = "Auto-generated movements cannot be edited." });

        if (dto.SourceType != MoneyMovementEntityType.External && !dto.SourceId.HasValue)
            return BadRequest(new { message = "SourceId is required when SourceType is not External." });

        if (dto.DestinationType != MoneyMovementEntityType.External && !dto.DestinationId.HasValue)
            return BadRequest(new { message = "DestinationId is required when DestinationType is not External." });

        movement.SourceType = dto.SourceType;
        movement.SourceId = dto.SourceId;
        movement.DestinationType = dto.DestinationType;
        movement.DestinationId = dto.DestinationId;
        movement.Amount = dto.Amount;
        movement.MovementDate = dto.MovementDate;
        movement.MovementType = dto.MovementType;
        movement.Note = dto.Note;

        await _db.SaveChangesAsync();
        return Ok(movement);
    }

    [HttpDelete("{id}")]
    public async Task<ActionResult> Delete(int id)
    {
        var movement = await _db.MoneyMovements.FirstOrDefaultAsync(m => m.Id == id && m.UserId == UserId);
        if (movement is null) return NotFound();

        if (movement.IsAutoGenerated)
            return BadRequest(new { message = "Auto-generated movements cannot be deleted." });

        _db.MoneyMovements.Remove(movement);
        await _db.SaveChangesAsync();

        return NoContent();
    }
}
