export type MoneyMovementEntityType = 'BankAccount' | 'Loan' | 'CreditCard' | 'External';
export type MovementType = 'LoanFunding' | 'LoanPayment' | 'CardPayment' | 'Transfer' | 'Deposit' | 'Withdrawal' | 'TradePnl' | 'TradeFee';

export interface MoneyMovement {
  id: number;
  sourceType: MoneyMovementEntityType;
  sourceId: number | null;
  sourceName: string;
  destinationType: MoneyMovementEntityType;
  destinationId: number | null;
  destinationName: string;
  amount: number;
  movementDate: string;
  movementType: MovementType;
  note?: string;
  isAutoGenerated: boolean;
  relatedPaymentId?: number | null;
  relatedExpenseId?: number | null;
  relatedTradeId?: number | null;
  createdAt: string;
  updatedAt: string;
}

export interface MoneyMovementCreate {
  sourceType: MoneyMovementEntityType;
  sourceId?: number | null;
  destinationType: MoneyMovementEntityType;
  destinationId?: number | null;
  amount: number;
  movementDate: string;
  movementType: MovementType;
  note?: string;
}
