import { Component, ChangeDetectorRef, OnInit, inject, input, signal } from '@angular/core';
import { CommonModule, CurrencyPipe } from '@angular/common';
import { LocalDatePipe } from './local-date.pipe';
import { RouterLink } from '@angular/router';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { MoneyMovementService } from '../core/services/money-movement.service';
import { MoneyMovement, MoneyMovementEntityType, MovementType } from '../core/models/money-movement.model';

@Component({
  selector: 'app-entity-movements',
  standalone: true,
  imports: [CommonModule, MatIconModule, MatButtonModule, CurrencyPipe, LocalDatePipe, RouterLink],
  template: `
    @if (movements().length > 0) {
      <div class="movements-section">
        <div class="section-header">
          <h3><mat-icon class="section-icon">sync_alt</mat-icon> Money Flow</h3>
          <a mat-button routerLink="/money-movements" class="view-all-btn">View All</a>
        </div>
        <div class="movements-list">
          @for (m of movements(); track m.id) {
            <div class="movement-row">
              <div class="movement-icon" [class]="'mi-' + m.movementType">
                <mat-icon>{{ typeIcon(m.movementType) }}</mat-icon>
              </div>
              <div class="movement-info">
                <span class="movement-label">
                  <span class="type-badge" [class]="'type-' + m.movementType">{{ typeLabel(m.movementType) }}</span>
                  @if (m.isAutoGenerated) {
                    <mat-icon class="auto-icon">auto_awesome</mat-icon>
                  }
                </span>
                <span class="movement-flow">
                  {{ m.sourceName }} <mat-icon class="flow-arrow">arrow_forward</mat-icon> {{ m.destinationName }}
                </span>
                <span class="movement-date">{{ m.movementDate | localDate:'mediumDate' }}</span>
              </div>
              <span class="movement-amount">{{ m.amount | currency }}</span>
            </div>
          }
        </div>
      </div>
    }
  `,
  styles: [`
    .movements-section { margin-top: var(--spacing-md); }
    .section-header {
      display: flex; align-items: center; justify-content: space-between;
      margin-bottom: var(--spacing-sm);
    }
    .section-header h3 {
      margin: 0; font-size: 1rem; font-weight: 600;
      display: flex; align-items: center; gap: 6px;
    }
    .section-icon { font-size: 20px; width: 20px; height: 20px; color: var(--color-primary); }
    .view-all-btn { font-size: 0.8125rem; }
    .movements-list { display: flex; flex-direction: column; gap: 8px; }
    .movement-row {
      display: flex; align-items: center; gap: 12px;
      padding: 12px;
      background: var(--color-surface);
      border-radius: var(--radius-md);
      box-shadow: var(--shadow-sm);
    }
    .movement-icon {
      width: 36px; height: 36px; min-width: 36px;
      border-radius: 8px;
      display: flex; align-items: center; justify-content: center;
    }
    .movement-icon mat-icon { font-size: 20px; width: 20px; height: 20px; }
    .mi-LoanFunding { background: rgba(33,150,243,0.1); color: #1976d2; }
    .mi-LoanPayment { background: rgba(76,175,80,0.1); color: #388e3c; }
    .mi-CardPayment { background: rgba(156,39,176,0.1); color: #7b1fa2; }
    .mi-Transfer { background: rgba(0,150,136,0.1); color: #00796b; }
    .mi-Deposit { background: rgba(255,152,0,0.1); color: #f57c00; }
    .mi-Withdrawal { background: rgba(244,67,54,0.1); color: #d32f2f; }
    .movement-info { flex: 1; display: flex; flex-direction: column; gap: 2px; }
    .movement-label { display: flex; align-items: center; gap: 6px; }
    .type-badge {
      padding: 2px 6px; border-radius: 10px;
      font-size: 0.625rem; font-weight: 600; white-space: nowrap;
    }
    .type-LoanFunding { background: rgba(33,150,243,0.1); color: #1976d2; }
    .type-LoanPayment { background: rgba(76,175,80,0.1); color: #388e3c; }
    .type-CardPayment { background: rgba(156,39,176,0.1); color: #7b1fa2; }
    .type-Transfer { background: rgba(0,150,136,0.1); color: #00796b; }
    .type-Deposit { background: rgba(255,152,0,0.1); color: #f57c00; }
    .type-Withdrawal { background: rgba(244,67,54,0.1); color: #d32f2f; }
    .auto-icon { font-size: 12px; width: 12px; height: 12px; color: var(--color-stat-purple); }
    .movement-flow {
      font-size: 0.8125rem; color: var(--color-text-secondary);
      display: flex; align-items: center; gap: 4px;
    }
    .flow-arrow { font-size: 14px; width: 14px; height: 14px; color: var(--color-text-muted); }
    .movement-date { font-size: 0.6875rem; color: var(--color-text-muted); }
    .movement-amount { font-weight: 700; font-size: 0.9375rem; color: var(--color-success); white-space: nowrap; }
  `]
})
export class EntityMovementsComponent implements OnInit {
  entityType = input.required<MoneyMovementEntityType>();
  entityId = input.required<number | string>();

  private movementService = inject(MoneyMovementService);
  private cdr = inject(ChangeDetectorRef);

  movements = signal<MoneyMovement[]>([]);

  ngOnInit(): void {
    this.movementService.getAll({
      entityType: this.entityType(),
      entityId: +this.entityId()
    }).subscribe(movements => {
      this.movements.set(movements);
      this.cdr.detectChanges();
    });
  }

  typeLabel(type: MovementType): string {
    const labels: Record<string, string> = {
      LoanFunding: 'Funding', LoanPayment: 'Payment', CardPayment: 'Card Payment',
      Transfer: 'Transfer', Deposit: 'Deposit', Withdrawal: 'Withdrawal'
    };
    return labels[type] || type;
  }

  typeIcon(type: MovementType): string {
    const icons: Record<string, string> = {
      LoanFunding: 'account_balance', LoanPayment: 'payments', CardPayment: 'credit_card',
      Transfer: 'sync_alt', Deposit: 'arrow_downward', Withdrawal: 'arrow_upward'
    };
    return icons[type] || 'swap_horiz';
  }
}
