using System.ComponentModel.DataAnnotations;
using Pulse.Core.Models.Enums;

namespace Pulse.Core.Models;

public class MoneyMovement
{
    public int Id { get; set; }

    public MoneyMovementEntityType SourceType { get; set; }
    public int? SourceId { get; set; }

    public MoneyMovementEntityType DestinationType { get; set; }
    public int? DestinationId { get; set; }

    public decimal Amount { get; set; }

    public DateTime MovementDate { get; set; }

    public MovementType MovementType { get; set; }

    [MaxLength(500)]
    public string? Note { get; set; }

    public bool IsAutoGenerated { get; set; }

    public int? RelatedPaymentId { get; set; }

    public int? RelatedExpenseId { get; set; }

    public int? RelatedTradeId { get; set; }

    public string? UserId { get; set; }

    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }
}
