const INSTITUTION_ICONS: Record<string, string> = {
  chase: 'account_balance',
  'jp morgan': 'account_balance',
  'jpmorgan': 'account_balance',
  'bank of america': 'account_balance',
  'bofa': 'account_balance',
  wells: 'water_drop',
  'wells fargo': 'water_drop',
  citi: 'location_city',
  citibank: 'location_city',
  capital: 'star',
  'capital one': 'star',
  amex: 'card_membership',
  'american express': 'card_membership',
  discover: 'explore',
  usaa: 'shield',
  navy: 'anchor',
  'navy federal': 'anchor',
  pnc: 'domain',
  'us bank': 'flag',
  'u.s. bank': 'flag',
  td: 'forest',
  'td bank': 'forest',
  ally: 'speed',
  sofi: 'rocket_launch',
  marcus: 'savings',
  goldman: 'savings',
  fidelity: 'candlestick_chart',
  schwab: 'candlestick_chart',
  'charles schwab': 'candlestick_chart',
  vanguard: 'trending_up',
  robinhood: 'show_chart',
  etrade: 'monitoring',
  'e*trade': 'monitoring',
  merrill: 'diamond',
  'merrill lynch': 'diamond',
  morgan: 'corporate_fare',
  'morgan stanley': 'corporate_fare',
  coinbase: 'currency_bitcoin',
  apple: 'phone_iphone',
  'apple card': 'phone_iphone',
  amazon: 'shopping_cart',
  costco: 'storefront',
  target: 'storefront',
  walmart: 'storefront',
  'home depot': 'hardware',
  lowes: 'hardware',
  "lowe's": 'hardware',
  barclays: 'account_balance',
  synchrony: 'sync',
  paypal: 'payments',
  venmo: 'send',
  zelle: 'bolt',
  suntrust: 'wb_sunny',
  truist: 'wb_sunny',
  regions: 'public',
  huntington: 'park',
  keybank: 'key',
  key: 'key',
  fifth: 'looks_5',
  'fifth third': 'looks_5',
  citizens: 'groups',
  bmo: 'landscape',
  hsbc: 'language',
  'wells fargo advisors': 'trending_up',
  wealthfront: 'auto_graph',
  betterment: 'auto_graph',
  prosper: 'trending_up',
  lending: 'handshake',
  'lending club': 'handshake',
  upstart: 'rocket',
  sallie: 'school',
  'sallie mae': 'school',
  navient: 'school',
  nelnet: 'school',
  fedloan: 'school',
  mohela: 'school',
  great: 'school',
  'great lakes': 'school',
  quicken: 'home',
  rocket: 'rocket_launch',
  'rocket mortgage': 'rocket_launch',
  car: 'directions_car',
  auto: 'directions_car',
  vehicle: 'directions_car',
  student: 'school',
  mortgage: 'house',
  home: 'home',
  personal: 'person',
  medical: 'local_hospital',
  dental: 'medical_services',
};

export function inferInstitutionIcon(name: string | null | undefined, fallback = 'account_balance'): string {
  if (!name) return fallback;
  const lower = name.toLowerCase().trim();
  if (INSTITUTION_ICONS[lower]) return INSTITUTION_ICONS[lower];
  for (const [keyword, icon] of Object.entries(INSTITUTION_ICONS)) {
    if (lower.includes(keyword) || keyword.includes(lower)) return icon;
  }
  return fallback;
}
